### ISSUE TITLE
Add e621 Support

### ISSUE THREAD

**Issue by kupiakos** [kupiakos/LapisMirror#20]
[Example](https://www.reddit.com/r/zootopia/comments/4h2i4s/someones_suspicious_by_weaver/)

**Comment by Shugabuga** [comment]
*and e926.net, as they are the same site (but e621 is NSFW).

**Comment by kupiakos** [comment]
Ah, makes sense. I'm don't really ever use either,, so this sort of undocumented expertise is very useful.

**Comment by Shugabuga** [comment]
TBH, I just found that out while making a plugin for Derpibooru. They both are booru sites (like mspabooru.com, any site I've mentioned on this issue's page, and any other site mentioned [here](http://knowyourmeme.com/memes/sites/danbooru)), and I was hoping they had similar API endpoints, but they don't. 

Also found out how to make plugins finally! Just have a few bugs to iron out and I can send in a PR for Derpibooru! 🎆

**Comment by Shugabuga** [comment]
Submitted Derpibooru plugin via PR.

In news relating to this issue: [I did a thing](https://www.reddit.com/r/heyitsshugatest/comments/4xeido/e926_api_mirror_thingy/d6eqyqs).

Edit: Just added a new thing, doing some tests still (not ready for a full release/PR)
