### ISSUE TITLE
Invalid syntax on line 140?

### ISSUE THREAD

**Issue by Shugabuga** [kupiakos/LapisMirror#24]
Getting this error when running `lapis.py` from Terminal:

```
File "lapis.py", line 140
    def call_plugin_function(self, func_name: str, *args, **kwargs) -> list:
                                            ^
SyntaxError: invalid syntax
```

Using the latest version of LapisMirror.

**Comment by spiral6** [comment]
I've had this happen before when checking it for PEP 8 guidelines. Never when running it. Unsure why this issue exists. Message me on reddit /u/spiral6 and I'll see if I can help out.

**Comment by Shugabuga** [comment]
Got it. Will continue there.

**Edit: Sent as /u/HeyItsShuga.**

**Comment by kupiakos** [comment]
Are you using Python 3?

**Comment by Shugabuga** [comment]
Now I am, and that fixed it!
