### ISSUE TITLE
Add FurAffinity Support

### ISSUE THREAD

**Issue by kupiakos** [kupiakos/LapisMirror#26]
[As requested by /r/zootopia](https://redd.it/4wghdd).

[Example for testing](https://redd.it/4wvqgy).

**Comment by Shugabuga** [comment]
I don't know if this would help, but it seems like there are some custom FurAffinity APIs on GitHub [here](https://github.com/search?l=Python&q=furaffinity&ref=searchresults&type=Repositories&utf8=%E2%9C%93).

**Comment by kupiakos** [comment]
@Shugabuga Funny you mention that. I've been using [this](https://github.com/boothale/faexport/blob/master/lib/faexport/scraper.rb) as a reference point for which CSS selectors would be best.

EDIT: I'm mostly done with the architecture of the plugin; I'm putting it all together now.

**Comment by Shugabuga** [comment]
I don't know if you prefer ID or class for scraping images from CSS selectors, but here's a few noteworthy things I noticed on how FA organizes user-friendly, non-CDN pages:

`#submissionImg` targets the submission image
`td .cat [href*='/user/']` targets the username
`#keywords` targets the tags
`td .cat b` targets the post title

Here's a page with those CSS rules getting some styling...

![screencapture-sfw-furaffinity-net-view-20808689-1470790832233](https://cloud.githubusercontent.com/assets/10801851/17538549/82cf7eba-5e74-11e6-8449-fbf478ef3c70.png)

...with this code:

```
#submissionImg {background-color:red} /*image*/
td .cat [href*='/user/'] {background-color:pink} /*username*/
#keywords {background-color:cyan} /*tags*/
td .cat b {background-color:yellow} /*title*/
```

I hope that helps in the slightest way! :)

**Comment by kupiakos** [comment]
Thanks! I'm using `td.cat a` for the author, and `td.cat b` for the title. I'm also designing support for reverse-lookup from the FA CDN given that it seems to be very prevalent on /r/zootopia.

**Comment by Shugabuga** [comment]
That would be nice! If not, you can just take the image on the CDN page and the author from the URL using regex kinda like this (pardon my lack of regex skills):

`https?://(*\.)?facdn\.net/art/<user>/*`

**Comment by kupiakos** [comment]
@Shugabuga Go ahead and check out commit 00974cb if you'd like.

**Comment by Shugabuga** [comment]
Will do! Thanks!
