### ISSUE TITLE
Link to GIFVs instead of GIFs

### ISSUE THREAD

**Issue by Vicyorus** [kupiakos/LapisMirror#30]

**Comment by Shugabuga** [comment]
Do you happen to have an example of a GIF being mirrored so I can take a look?

**Comment by Vicyorus** [comment]
@Shugabuga https://www.reddit.com/r/stevenuniverse/comments/4zkk3z/oldtimey_pearl_and_garnet_animation/d6wjq4u

**Comment by Shugabuga** [comment]
@Vicyorus  Like [this](https://i.imgur.com/iGAq9SV.gifv)?

**Comment by Vicyorus** [comment]
@Shugabuba Well, yes it'd help if imgur wouldn't redirect you to their crappy site, but yes, adding a "v" at the end. Kupiakos told me to open an issue to remind me of it, so I did.

**Comment by Shugabuga** [comment]
Yeah, and that's great that you did! 😄

I don't really know how the imgur export plugin works (or any export plugins), but maybe @kupiakos can add a link to both GIF and GIFV??? Just an idea.

**Comment by spiral6** [comment]
I think I've got it. In line 308 of lapis.py, 

the code `links_display = ''.join(links_display_parts)` is combining the links into a string. A simple regex check and replace ".gif" with ".gifv" in said string, and then reassignment should do it. Should work with every plugin as this is processed after the export data returns.

**Comment by kupiakos** [comment]
Any code involving gifv should be in the imgur export plugin, not in
lapis.py. Also, I'm not sure it's guaranteed that animations end in .gif on
imgur.

**Comment by spiral6** [comment]
Got it, I see where it's being exported in imgur.py.

Maybe there's a way to get the mime type of an Imgur URL and determine what the proper URL should be from there? I'll take a look into that.

**Comment by Shugabuga** [comment]
Also, it may be worth noting that GIFVs on Imgur (tested on the one provided by Vicyorus using `cURL`) have a MIME type of `text/html; charset=utf-8`, but the normal GIFs are normal (`image/gif`).

**Comment by spiral6** [comment]
Hmm, what about... there's an interesting thing with the way imgur works. What if you just linked every imgur image (not albums) as a .gifv? Regardless of the extension, if it exists, if you replace the extension with a .gifv, it should always return the correct type. If you linked say, a .jpg image with .gifv, a .jpg image would be returned. If you linked a .gif image with .gifv, a .webm image would be returned.

**Comment by kupiakos** [comment]
@spiral6 I'd prefer not. The `HEAD` request that is done normally in many cases could be used to add information from the import plugin about whether it's animated or not, if it doesn't already. A `HEAD` request will contain the MIME-type of the content, and we can check if it's an animated format during import.
