### ISSUE TITLE
e926: Uploader being credited as artist

### ISSUE THREAD

**Issue by Shugabuga** [kupiakos/LapisMirror#33]
**Note: I'll take care of this. This is for my own reference.**

Use `artist` instead of `author` when calling the JSON. `artist` is an array, though, which means it likely would have to call the API slightly differently.

Maybe by changing `uploader = json['author']` to `uploader = json.artist['0']` or something like that?

**Comment by Shugabuga** [comment]
Fixed in upcoming PR. And no, that syntax doesn't work.

**Comment by kupiakos** [comment]
BTW, when submitting a PR, if you have in the comments of the PR or a commit the term
`Fixes #33` or `Resolves #33`, among similar things, the issue will automatically be closed when it's pulled in.

**Comment by Shugabuga** [comment]
Ah, I thought that was just in the titles...

Thanks though!
