### ISSUE TITLE
Feature Request: Link to Blog picture came from

### ISSUE THREAD

**Issue by martinjh99** [kupiakos/LapisMirror#41]
When its posting the tumblr blog/DA page (wherever it got the pic from) that it got the picture from how about making the name of the tumblr a link to said blog/DA page?

Eg:

Mirrored post from the tumblr blog "BOOM CLAP":

With BOOM CLAP being a link to dashingicecream.tumblr.com or the exact page where the pic was from up to you...

**Comment by Shugabuga** [comment]
I don't this would be *too* difficult to implement (in fact, some newer plugins like the Derpibooru and FA ones do this IIRC).

I would propose a reply like this:

Mirrored [post](http://illumineighti.tk/#javascript:alert("Let's-say-this-is-the-page-where-we-got-the-image-from-or-the-URL-of-the-post-submitted.");window.location="https://github.com/kupiakos/LapisMirror/issues/41") from the tumblr blog "[BOOM CLAP](https://dashingicecream.tumblr.com/)":

...with the [post](http://illumineighti.tk/#javascript:alert("Let's-say-this-is-the-page-where-we-got-the-image-from-or-the-URL-of-the-post-submitted.");window.location="https://github.com/kupiakos/LapisMirror/issues/41") link being the exact page where the picture was, and [BOOM CLAP](https://dashingicecream.tumblr.com/) being the author's main page / Tumblr blog home.

Idk if I have time to implement this, but I may get around to it eventually.

**Comment by martinjh99** [comment]
No worries mate :) If I could program in Python might have given it a go myself!

**Comment by Shugabuga** [comment]
Yeah, holidays and other projects is making it hard to find time to code it and (most importantly) test it.

**Comment by spiral6** [comment]
I'll give it a shot on working on it, will also add it to VelvetBot's functionality.

**Comment by spiral6** [comment]
@Shugabuga Additionally, is there a subreddit I should create or work with to test functionality of the bots?

**Comment by Shugabuga** [comment]
/r/HeyItsShugaTest (my test subreddit) or /r/BotTest (for any bot) are both fine if you want to test it. My subreddit already is full of TheMirrorPool test posts. Also, if you PR the feature, I'll add it to TheMirrorPool (I try to keep it updated).

**Comment by spiral6** [comment]
#42

**Comment by kupiakos** [comment]
Does this handle reblogs properly? For example, if user A posts picture B, and user C reblogs picture B, which then has the reblogged link posted on Reddit, will the link in the mirror comment go to User A's or User B's blog? If it just posts what the original Reddit link was, I see no reason to put it in the comment.

**Comment by spiral6** [comment]
Not sure, although if it does post only the reblog, it should just be a quick fix by using tumblr's API or scraping to figure out where the original is from. Then I can post the original link in the comment. I'll test it soon.

**Comment by spiral6** [comment]
Alright, updated pull request that now determines reblog information, if it exists, and now posts the original author URL to post, blog, and name of blog.

**Comment by Shugabuga** [comment]
Neat!

**Comment by spiral6** [comment]
Tumblr merged, now to work on the DeviantArt plugin.

**Comment by spiral6** [comment]
Works according to test. Should be able to close this issue once this is merged.
