### ISSUE TITLE
Lapis fails on "sensitive" Tumblr material

### ISSUE THREAD

**Issue by Shugabuga** [kupiakos/LapisMirror#51]
http://reddit.com/r/zootopia/comments/7qn4sq/my_hero_zpd/dsqdx6d

The Tumblr blog linked in the above post is not viewable with safe mode enabled, and it seems like Lapis couldn't mirror the post as a result. Lapis posts a comment with the proper blog title and direct link, but nothing is mirrored.

**Comment by kupiakos** [comment]
Not sure this will actually be a problem anymore now that Tumblr has been stupid.
